services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: fitnesdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./server
    depends_on:
      - db
      - redis
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dev
      DB_PASS: devpass
      DB_NAME: fitnesdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: key

  frontend:
    build: ./client
    depends_on:
      - backend

  redis:
   image: redis:7-alpine

  proxy:
    image: nginx:1.26-alpine
    ports:
      - "80:80" #exposea frontend on port 80
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend 
    entrypoint: /bin/sh -c '
      if [ ! -f /etc/letsencrypt/live/devops-vm-30.lrk.si/fullchain.pem ]; then
        mkdir -p /etc/letsencrypt/live/devops-vm-30.lrk.si;
        apk add --no-cache openssl >/dev/null 2>&1 || true;
        openssl req -x509 -nodes -newkey rsa:2048 -days 1
          -keyout /etc/letsencrypt/live/devops-vm-30.lrk.si/privkey.pem
          -out /etc/letsencrypt/live/devops-vm-30.lrk.si/fullchain.pem
          -subj "/CN=devops-vm-30.lrk.si";
      fi;
      nginx -g "daemon off;"; '

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  db_data:

