services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: fitnesdb
    volumes:
      - db_data:/var/lib/postgresql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./server
    depends_on:
      - db
      - redis
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dev
      DB_PASS: devpass
      DB_NAME: fitnesdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: key
    ports:
      - "5000:3001"

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "8080:80"

  redis:
   image: redis

volumes:
  db_data:

