services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: fitnesdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./server
    depends_on:
      - db
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dev
      DB_PASS: devpass
      DB_NAME: fitnesdb
      JWT_SECRET: key
    ports:
      - "5000:3001"

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "80:80"

# proxy: