services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: fitnesdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./server
    depends_on:
      - db
      - redis
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dev
      DB_PASS: devpass
      DB_NAME: fitnesdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: key

  frontend:
    build: ./client
    depends_on:
      - backend

  redis:
   image: redis:7

  proxy:
    image: nginx:latest
    ports:
      - "80:80" #exposea frontend on port 80
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend 

volumes:
  db_data:

