apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: fitness
spec:
  selector:
    app: frontend
    track: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: fitness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      track: blue
  template:
    metadata:
      labels:
        app: frontend
        track: blue
    spec:
      containers:
        - name: frontend
          image: ghcr.io/acodes3/fitness-frontend:blue
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: fitness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      track: green
  template:
    metadata:
      labels:
        app: frontend
        track: green
    spec:
      containers:
        - name: frontend
          image: ghcr.io/acodes3/fitness-frontend:green
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
